### ISSUE TITLE
Peer id invalid

### ISSUE THREAD

**Issue by anikethjana1** [SpringsFern/TG-FileStreamBot#4]
**LOGS:**

`Instance is healthy. All health checks are passing.
[22/08/2024 06:58:54] {/app/.heroku/python/lib/python3.9/site-packages/pyrogram/dispatcher.py:366} ERROR - Peer id invalid: -1002229632110
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.9/site-packages/pyrogram/methods/advanced/resolve_peer.py", line 62, in resolve_peer
    return await self.storage.get_peer_by_id(peer_id)
  File "/app/.heroku/python/lib/python3.9/site-packages/pyrogram/storage/sqlite_storage.py", line 195, in get_peer_by_id
    raise KeyError(f"ID not found: {peer_id}")
KeyError: 'ID not found: -1002229632110'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.9/site-packages/pyrogram/dispatcher.py", line 353, in handler_worker
    await handler.callback(self.client, *args)
  File "/workspace/WebStreamer/bot/plugins/stream.py", line 41, in private_receive_handler
    await get_file_ids(False, inserted_id, multi_clients)
  File "/workspace/WebStreamer/utils/file_properties.py", line 20, in get_file_ids
    log_msg=await send_file(StreamBot, file_info['file_id'])
  File "/workspace/WebStreamer/utils/file_properties.py", line 119, in send_file
    return await client.send_cached_media(Var.BIN_CHANNEL, file_id)
  File "/app/.heroku/python/lib/python3.9/site-packages/pyrogram/methods/messages/send_cached_media.py", line 136, in send_cached_media
    peer = await self.resolve_peer(chat_id)
  File "/app/.heroku/python/lib/python3.9/site-packages/pyrogram/methods/advanced/resolve_peer.py", line 89, in resolve_peer
    peer_type = utils.get_peer_type(peer_id)
  File "/app/.heroku/python/lib/python3.9/site-packages/pyrogram/utils.py", line 345, in get_peer_type
    raise ValueError(f"Peer id invalid: {peer_id}")
ValueError: Peer id invalid: -1002229632110`

ONLY REQUIRED VARS ADDED , OPTIONAL SKIPPED.
![image](https://github.com/user-attachments/assets/51c06318-9330-4c7a-b49f-6789afd0a7f0)

**Comment by DeekshithSH** [comment]
If I am not wrong It was happening because pyrogram used in this repository is old
